### ISSUE TITLE
Allow switching between time and score based game modes on the fly

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#11]
> /set roundTime [#] ;Set the round time for this map in seconds. This value must be less than an hour, and only works if the server is configured to time maps of this mode.

Seems to imply that it is not possible to have some maps that are, for example, in ball game mode that end after 20 minutes, and some that end after someone scores 6 goals, without restarting the server and switching the setting in the server_configurator settings file, every time you switch between those maps.
Do you think you could fix/improve this?

**Comment by biell** [comment]
This change would require updates to the server code.  roundTime directly translates into commands provided by Xal's server patches.

**Comment by biell** [comment]
I'm not good enough at java and how the server patches work to implement this.  If it does get into server patches I will incorporate it, but for now it is a won't fix.
