### ISSUE TITLE
ball_3asteroids_reset

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#12]
#Bring ball out on ball_**half_court**

MAP 'ball_**3asteroids_reset**';

Is that alright?

Edit: bolding doesn't work inside code boxes, disappointing~

**Comment by biell** [comment]
This is correct if the map file is called `ball_3asteroids_reset.altx`  Is that the name of your map?

**Comment by kevATin** [comment]
Ah no I haven't tried that map yet, I was referring to the mention of "ball_half_court" in the script about "ball_3asteroids_reset". Was wondering if you used the half court script as a template and forgot to edit the comment.

**Comment by biell** [comment]
Yes, that must be what I did, that is a comment.  Sorry, didn't realize  I will fix in next code push.

**Comment by kevATin** [comment]
same with this issue ;)
