### ISSUE TITLE
javaHome using OpenJDK

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#20]
If I were to use OpenJDK-8 (or 11, or some other version) should I expect potential issues or is alti+server fully compatible with that?

After setting javaHome to "/usr/bin/java" can I safely delete the altitude/jre folder or is it still used for something? (disk space is my main concern here, 150mb for dozens of servers adds up on a 32gb sd card)

**Comment by biell** [comment]
You should be able to run just fine against OpenJDK.  It won't affect the alti+server, java is only used by Altitude itself.  I use OpenJDK-8.

My guess is that you can safely delete the directory, but I am not sure.  I would try it and see what happens.

**Comment by kevATin** [comment]
Seems fine so far~
