### ISSUE TITLE
[Quest for slim Alti Folder] resources

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#21]
Altitude is pretty lightweight, the only parts taking up a lot of space are the jre and the resources folders.
With jre gone; is it possible to trim down the resources one? Simply throwing it out results in alti+server throwing an error.
Is it worth trying to rip out parts that don't seem necessary for the server, or am I likely to run into errors at some point?

Alternatively, do you think I could create one main altitude folder with all base files, and all server folders just contain links to the files? (at least the ones that aren't being written to) Or will there be potential problems with dozens of servers accessing them?

**Comment by biell** [comment]
I would not delete anything in the `resources` folder.  I think it is all needed under different circumstances.

I am confident that your link method would work.

Also remember, that with `ALTITUDE_ROOT`, you only need one copy of `alti+server`.

**Comment by kevATin** [comment]
Too bad;
I guess I should really start using symlinks~

**Comment by biell** [comment]
I think your symlink idea is a good one.  You can symlink at the `resources` directory, so it should be easy.  You need local `log`, `maps`, and `servers`, and I think every other directory could be a symlink and shared.  Most (maybe all) of the files in the base directory can be sylinked too.
