### ISSUE TITLE
Long server and map names

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#22]
So the way I'm currently organizing stuff I'll have servers and maps use names like "mmorpg_overworld_southeast_city_football_indoor", extreme example, but still.
What are the limits for server and map name length? Anything I need to watch out for? Alti only accepts ASCII, right?

**Comment by biell** [comment]
Not much in the way of a limitation that I know of, just remember that it might scroll wherever the name is displayed, which isn't in many places.  Your example seems well within the likely limits.

**Comment by kevATin** [comment]
I see; thanks.
