### ISSUE TITLE
Bot Customization

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#24]
What are the limits of bots in alti?
Can I decide which bot(name) spawns where?
Can I shuffle bots around teams like players?
Can I get bots of varying difficulty to spawn?
Can I change bot difficulty mid game?
Can I set which planes, and perks they use?
Are there any ways to, either actively or passively, influence bot behaviour/movement?

Will it be possible to set up random encounters in the world maps? Eg: player moves around in region far away from city, random amount of bots spawn around player, difficulty is based on the player's level; etc

Or waves in a dungeon like map? First a handful of weak bots come, and then they get more and stronger with each new wave.

**Comment by biell** [comment]
> What are the limits of bots in alti?

Answers assume Xal Bot mods

> Can I decide which bot(name) spawns where?

Yes

> Can I shuffle bots around teams like players?

Yes

> Can I get bots of varying difficulty to spawn?

Yes

> Can I change bot difficulty mid game?

Yes, but you have to remove them, then re-add them at the new level.

> Can I set which planes, and perks they use?

Yes, `/botPlaneSetup`'s first argument is the bot number.  Or, use `0` for all bots.

> Are there any ways to, either actively or passively, influence bot behaviour/movement?

You can use the `/applyForce` command to nudge them around, but that isn't easy to use or control.

> 
> Will it be possible to set up random encounters in the world maps? Eg: player moves around in region far away from city, random amount of bots spawn around player, difficulty is based on the player's level; etc

Using a combination of `/overrideSpawnPoint` and `/assignTeam`, yes.

> 
> Or waves in a dungeon like map? First a handful of weak bots come, and then they get more and stronger with each new wave.

Yes, but you will have to remove and re-add the bots.  The player notification area will show them leaving and re-joining.

**Comment by kevATin** [comment]
Interesting stuff; the limitation of only having bots of the same difficulty on the map at a time is a bit restricting, but it should be fine~

**Comment by biell** [comment]
I said "Yes" to that question.  You can assign each bot it's own difficulty level.

**Comment by kevATin** [comment]
Oh I see; I must've misinterpreted the "Yes, but you have to remove them, then re-add them at the new level."-part. It was very late when I replied to that, from what I remember ~
