### ISSUE TITLE
Spoof Information in Server List/Browser

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#27]
Is it possible to spoof information like the amount of currently online players?
Since the mmorpg would be a network of servers where only the lobby server is visible and join-able, it would probably usually sit at 0 players while in reality dozens of players could be inside the game servers.
So I'd love to add the numbers of players on the network together and set them for the lobby server, and for that I'd need the ability to set that.

Next up would be spoofing the max player slots in the server list. At first this might simply sound like a fun gimmick rather than a useful feature, but I think this would work great together with the earlier feature.
Imagine if the number of players on the mmorpg network exceeds 64, it'd be 73/64 or something. Ideally the maximum player number could be the total number of all players that can fit on all maps or something, either way it should be higher, even if the actual number of slots for the mmorpg_lobby is just 64 or even less.
Something that comes to mind here, have there been tests on whether the client can handle numbers like that? Ideally it doesn't care, but if the client crashes or fails to display the server when it gets the packet that'd be bad.
Also I'm not sure how all of that works in detail, does the main alti server collect information of every listed server and then send that to the client, or does the alti main server just collect the IPs and then forward the list to the client and the client asks the individual servers? Depending on how that's handled this may be harder to do.

While we're at the topic of spoofing, if I remember correctly you mentioned potential game mode spoofing in Altitude a while ago.
Currently it's not possible, right? Would that be something that you could implement or would xal have to do something about that?
To be clear I'm just talking about the server list mode entry, nothing gameplay related.

**Comment by biell** [comment]
The central Altitude servers (Vapor Servers) actually are the ones who keep track of who is logged in where, and report on server statistics.  So, I don't think you could spoof it, because it comes from the clients, not the servers.  If people used a modified client, then maybe; but, I think I think that would cause other problems for the players.

You might be able to control/spoof max player slots by sending a larger number, but you wouldn't be able to control how many people were listed as being on the server.  Also, I would be careful here.  Altitude shares a lot of code between the server and the client, and so it would not surprise me if the vapor servers also share code.  A limit check for 64 max players in one place would probably exist for the clients and vapor servers, in which cases you could cause issues.

In the case of a failed verification step, I think the most likely outcome would be for the server to not display for users.

The vapor server sends all the information to the client.  A client will not send a packet to your server unless the player is actively trying to join.

Game mode override would require a modified server and client, that is why Xal never attempted to do anything with that.  He stuck directly to server changes only.  Rawr ran a modified client so that he would know that Bot's on his server (they started with "Mr." for a while) would show up properly as bots on his client.  It caused all kinds of havoc for keeping the game balanced when players left, so he stopped doing that thankfully.

**Comment by kevATin** [comment]
Argh I feared something like that; then I guess the current number of players will be displayed in the server name of the lobby server "MMORPG ______________ [Online Players: 71/300]".

It starts to make sense as to why sometimes servers display the wrong amount of players, when a client crashes or something.
I guess I could set up one hundred dummy accounts and one of them tells the vapor server that they've connected to the mmorpg lobby, for each player that is currently inside the mmorpg network. But that doesn't seem like a pretty solution.

Another option would be to run all all servers on the same ip and port, similar to how, to my knowledge, Minecraft server networks push around players with BungeeCord and similar software. Only a single server faces externally, and the clients still think they're on that server when in reality they're on a different one. I guess this could be done by remembering which player/ip is supposed to be connected to which server and then routing it around internally. But that would have relatively little payoff and would probably be a lot of work.
I think I'll go with putting the player amount in the server name.

> Game mode override would require a modified server and client

Ok, so the server list will ALWAYS display the game mode as being the prefix of the map name, or in the case of no known prefix; UNK.
And completely separate from that, the game itself will always interpret the game mode by the requirements inside the map being met, is that right?

**Comment by biell** [comment]
> It starts to make sense as to why sometimes servers display the wrong amount of players, when a client crashes or something.

Yes, that is exactly correct.

> I guess I could set up one hundred dummy accounts and one of them tells the vapor server that they've connected to the mmorpg lobby, for each player that is currently inside the mmorpg network. But that doesn't seem like a pretty solution.

That sounds like a lot of work for minimal gain, but I will leave that up to you.

> Another option would be to run all all servers on the same ip and port, similar to how, to my knowledge, Minecraft server networks push around players with BungeeCord and similar software. Only a single server faces externally, and the clients still think they're on that server when in reality they're on a different one. I guess this could be done by remembering which player/ip is supposed to be connected to which server and then routing it around internally. But that would have relatively little payoff and would probably be a lot of work.

I believe that would cause you all kinds of problems.   Remember that the Vapor server also talks to you on that port, and all the communication uses UDP.  If you got it to work, I would be very interested in your configuration.  But, I don't think it is possible.

> I think I'll go with putting the player amount in the server name.

Yeah, some naming conventions might help people  pick the right servers.  Keep in mind that you will have to deal with the situation that someone logs directly into a server that isn't your lobby.

> > Game mode override would require a modified server and client
> 
> Ok, so the server list will ALWAYS display the game mode as being the prefix of the map name, or in the case of no known prefix; UNK.

Yes.

> And completely separate from that, the game itself will always interpret the game mode by the requirements inside the map being met, is that right?

Yes.  It seems ridiculous, but yes.  So, you could make a tbd_foo map, rename it to ball_foo, the vapor server will tell everyone that if they join they will play ball, but when they connect, it will actually be tbd.

**Comment by kevATin** [comment]
> Yeah, some naming conventions might help people pick the right servers. Keep in mind that you will have to deal with the situation that someone logs directly into a server that isn't your lobby.

All servers other than the lobby server are in LAN mode (so they're hidden from the server list, and the server list isn't spammed with dozens of MMORPG maps), and in xal's whitelisted mode (so players can't join them without the automated system whitelisting them moments before they're transported to the new server).

Something that might be a problem; can the name of a server be changed/updated without requiring a server restart? Or more importantly will the vapor server become aware of that change and publish the new name? Because if not, then the idea of putting the current player amount in the server name might not end up working.

How are LAN servers handled in regards to the server list? Are LAN server's information directly discovered and requested by the client, or does the vapor server still interact with them but only broadcast them to servers on the clients network.

**Comment by biell** [comment]
You will need to restart the server for the name to change.  So, you can put the max players in the name, but not the number currently connected.

I have no idea how LAN servers differ.  I never thought that they worked the way you are describing, but maybe they do.  I certainly hadn't put much thought into it.  It makes a lot of sense, what you say.  I would be interested to hear about how you get that to work.

**Comment by kevATin** [comment]
Curses; ... I'm starting to get serious about that idea with the hundred dummy accounts...

I'll do some testing regarding LAN servers in the coming days~

**Comment by kevATin** [comment]
Btw a while ago I came up with a seemingly good solution for this problem;
Have the lobby server restart all 10 or so minutes while the rest of the server network keeps running. That way the player number in the lobby server name can be updated somewhat often, while it doesn't interfere much with gameplay.

Still haven't gotten around to test whether lan servers are able to be discovered by an offline client without the nimbly server list~

**Comment by biell** [comment]
That would use a lot of CPU.  The startup CPU for Altitude alone is probably equivalent to 10 players actually playing for 10 hours.
