### ISSUE TITLE
update port

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#29]
What is the "update" port used for?
alti+server seems to not be able to run multiple servers with the same update port, but the way that the vanilla server configurator looks like you could assume that it can handle multiple servers with one update port.
Is that so? Could this be added to alti+server?

**Comment by biell** [comment]
The altitude server is configured to allow multiple server inside one java process.  This is way more efficient on memory than running a dedicated java process for each server.  However, doing this would add a huge burden on the programming of the alti+server to keep all state by port and accept a log file interaction whereby multiple servers were constantly requiring maintenance.  So, I made the decision to only allow one altitude server per alti+server process.  This simplified the coding and reduced the number of bugs.  Unfortunately, this choice means it takes more memory and a little more cpu to make multiple altitude servers run on the same guest.

I am not prepared to add multiple server support to alti+server, there would be so many bugs introduced and troubleshooting them would become much harder.

**Comment by kevATin** [comment]
I see that's too bad;
But what Is the update-port actually used for? Is it just relevant for the server list? If so, might it be possible to ignore the update-port when the server is in LAN mode, and still have everything work as intended?

**Comment by biell** [comment]
I am not 100% sure what it does, but you can change it.  So, just give each update port its own port.  I have a server with 4 alti+server processes, the first pair (updatePort,serverPort) of ports is 27275,27276, then I use 27277,27278, and so on.

**Comment by kevATin** [comment]
Yeah I do the same right now; I'll probably play around a bit more with that setting~
