### ISSUE TITLE
[Question] PowerupPickup vs PowerupAutoUse

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#32]
What is the difference between these two, and how do they work exactly? Does the later only apply to Health?

**Comment by biell** [comment]
Yes, Health is the only auto-use.  To give you an idea about what I think of them being different log entries, here is my code for auto-use:

```
    'powerupAutoUse'    => sub {
         $HOOKS{'powerupPickup'}->(@_);
    },
```

I literally just send the `powerupAutoUse` event and player to the `powerupPickup` hook, and deal with both log entries in the same hook.
