### ISSUE TITLE
Undefined subroutine &team::left

### ISSUE THREAD

**Issue by lhallam** [biell/alti-server#4]
Here's the error from Jonus's test server, I'm not sure what was happening at the time:
Undefined subroutine &team::left called at alti-server/alti+server line 5507, <GEN5> line 851

**Comment by biell** [comment]
Fixed in most recent code update.  Proper function name is "map::left".  "team" is not a valid package name.

**Comment by biell** [comment]
I missed 1 invalid reference to the "team" package in the original update.  All references have been updated in commit cdb27958336f5271fef151c98ebfbe7b099764a1 .
