### ISSUE TITLE
1de Co-op map timer doesn't reset between rounds

### ISSUE THREAD

**Issue by lhallam** [biell/alti-server#5]
Just had a pretty good run on a 1de map, ~1min, the timer at the end showed 4mins, I guess it wasn't reset for the new round.

Any easy fix for this?

**Comment by biell** [comment]
Resolved in 8e1fcc2 with the help of 88c3df9

Timers start on Coop when the first player spawns, not when objectiveGameStart is seen.  But, I still needed to reset the first spawn trigger on objectiveGameStart, so the server would know what to do.  This methodology allows players to discuss the game plan after spawn is available without that discussion negatively impacting their record.  Unless, of course, they are playing with Leeroy Jenkins ;)

Thanks.
