### ISSUE TITLE
Alti+Server complains about the "list" of admins not being an array when it's only one

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#6]
Alti+Server threw an error when I started it with only a single entry in the admin list (set via server_configurator). It seems to assume it always gets an array of entries, which isn't the case if it's only one. 
What I didn't test was if there is also an error when starting with zero entries, since that technically also shouldn't be an array.

**Comment by biell** [comment]
Can you look in our `stdout.txt` file and send me the exact output, with a few lines of context before and after the message?  It will help me narrow down where this issue resides.

Thanks.

**Comment by kevATin** [comment]
Starting alti+server with a single uuid in the admins list causes the server to stop shortly after being started without getting a chance to see much in the terminal because it immediately overwrites the text making only a "9" visible. Curses being funny i guess.
By doing ./alti+server > LOGFILE I was able to find out that the reason it stopped was "Not an ARRAY reference at ./alti+server line 2909. (which is the list of admins)
This error is not logged in stdout; that only shows:

> Using /usr/bin/geoiplookup (good)
> Using /bin/ping (good)
> using JSON::XS (good)
> Using /usr/bin/lzma (good)
> Using/sbin/ip (good)
> Using /usr/bin/curl (good)
> Using /usr/bin/curl (good)
> Using /usr/bin/curl (good)
> Using /usr/bin/curl (good)
> using DBD::SQLite (ok)

Yes sometimes the "u/U" in using is small and sometimes big ;)
Not sure why it confirms curl 4 times.
Either way looking at the LOGFILE output, the stdout.txt log perfectly aligns because the error happens right afterwards.
Adding a second entry in the admins list fixes the issue.
When the list has zero entries the alti+server apparently has no issue with it not being an array. Not even any mention of it in the log~

**Comment by biell** [comment]
Got it, thanks.  I was looking in the wrong place.  I can do something about that.

**Comment by biell** [comment]
Updated the using's to always use a capital U in 050d9be7e0d9a27422dab27debdebbac98d89c11

Fixed the alti+server code to handle both cases, when adminsByVaporID has 1 (non-array) and many (array) data structure configurations in 050d9be7e0d9a27422dab27debdebbac98d89c11
