### ISSUE TITLE
Bot suffix?

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#9]
Since bot prefixes are an option I was wondering if you could add suffixes too.

**Comment by biell** [comment]
The bot name stuff comes from the server mods.  It provides only two mechanisms, a prefix, and the names.  Since you can set the names as you like, you could set the suffix yourself to be part of the bot name.  So, for "Bot 1st", you could set prefix to "Bot " and the first bot name to "1st"

**Comment by kevATin** [comment]
Yeah it's not really something high priority, just thought it'd be nice to have since prefixes are a thing too.
With "server mods" you're referring to the xx-patch ( https://gitlab.com/alti2d/server_patches ), right? Maybe I'll open an issue there to bother xal ;)

**Comment by biell** [comment]
Yes, Xal's server patches/mods are what I refer to as "xx" after his old nick "x.x".  If he were to add a feature like this, then I would add a corresponding feature to my code as I try to keep parity with his work.  That being said, I don't think he will do so.
